### ISSUE TITLE
getting cors 

### ISSUE THREAD

**Issue by fms12** [Aniket-git-hub/32si#2]
![image](https://github.com/Aniket-git-hub/32si/assets/68012074/9905a4bd-afff-4362-9ac8-094a3908906e)

I'm getting the same issue while logging and registering. if you solve this issue please help me also 

thank you !

**Comment by Aniket-git-hub** [comment]
i am still working on this project. so, you are getting this error. If you want to use, it you setup the project locally and then try. But as of now am still working on it. If you still want to try the live version use  [this](https://32si.vercel.app/login) link
